import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { CircleHelp, Loader2, MessageCircle, Plus, Send, Tag, UserRound, X } from 'lucide-react';
import { communityService } from '../services/communityService';
import type { CommunityQuestion } from '../types/community';

const formatDate = (value: string) => new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });

export const CommunityPage: React.FC = () => {
  const queryClient = useQueryClient();
  const [page, setPage] = useState(0);
  const [composerOpen, setComposerOpen] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [tags, setTags] = useState('');
  const [answer, setAnswer] = useState('');
  const questionsQuery = useQuery({ queryKey: ['communityQuestions', page], queryFn: () => communityService.getQuestions(page) });
  const questionQuery = useQuery({ queryKey: ['communityQuestion', selectedId], queryFn: () => communityService.getQuestion(selectedId!), enabled: !!selectedId });
  const invalidateQuestions = () => queryClient.invalidateQueries({ queryKey: ['communityQuestions'] });
  const postQuestion = useMutation({ mutationFn: communityService.createQuestion, onSuccess: () => { invalidateQuestions(); setComposerOpen(false); setTitle(''); setContent(''); setTags(''); toast.success('Your question has been posted.'); }, onError: () => toast.error('Unable to post the question. Please try again.') });
  const postAnswer = useMutation({ mutationFn: () => communityService.createAnswer(selectedId!, answer), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['communityQuestion', selectedId] }); invalidateQuestions(); setAnswer(''); toast.success('Answer posted.'); }, onError: () => toast.error('Unable to post the answer. Please try again.') });
  const submitQuestion = (event: React.FormEvent) => { event.preventDefault(); if (title.trim().length < 8 || content.trim().length < 15) { toast.error('Use a descriptive title and add at least 15 characters of detail.'); return; } postQuestion.mutate({ title, content, tags }); };
  const submitAnswer = (event: React.FormEvent) => { event.preventDefault(); if (answer.trim().length < 5) { toast.error('Your answer needs at least 5 characters.'); return; } postAnswer.mutate(); };
  const selectedQuestion = questionQuery.data;

  return <div className="max-w-6xl mx-auto space-y-6 pb-10">
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 border-b border-slate-200/60 dark:border-dark-border/40 pb-6"><div><h1 className="flex items-center gap-2 text-3xl font-extrabold font-heading text-slate-800 dark:text-white"><CircleHelp className="h-7 w-7 text-brand-650" /> CareerForge Q&A</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Ask placement questions, share knowledge, and help fellow students succeed.</p></div><button onClick={() => setComposerOpen(true)} className="inline-flex items-center justify-center gap-2 bg-brand-650 hover:bg-brand-700 text-white px-4 py-2.5 rounded-xl text-sm font-bold shadow-sm"><Plus className="h-4 w-4" /> Ask a question</button></div>
    {questionsQuery.isLoading ? <div className="space-y-4 animate-pulse">{[1, 2, 3].map(i => <div key={i} className="h-40 rounded-2xl bg-slate-200 dark:bg-zinc-800" />)}</div> : questionsQuery.data?.content.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 dark:border-dark-border py-20 text-center"><CircleHelp className="h-10 w-10 mx-auto text-slate-400" /><p className="mt-3 font-bold text-slate-700 dark:text-slate-200">No questions yet</p><p className="mt-1 text-sm text-slate-500">Start the conversation by asking the first one.</p></div> : <div className="space-y-4">{questionsQuery.data?.content.map(question => <QuestionCard key={question.id} question={question} onOpen={() => setSelectedId(question.id)} />)}</div>}
    {(questionsQuery.data?.totalPages ?? 0) > 1 && <div className="flex justify-between items-center pt-2"><button disabled={page === 0} onClick={() => setPage(p => p - 1)} className="px-4 py-2 rounded-xl border text-sm disabled:opacity-50">Previous</button><span className="text-sm text-slate-500">Page {page + 1} of {questionsQuery.data?.totalPages}</span><button disabled={page >= (questionsQuery.data?.totalPages ?? 1) - 1} onClick={() => setPage(p => p + 1)} className="px-4 py-2 rounded-xl border text-sm disabled:opacity-50">Next</button></div>}
    {composerOpen && <Modal onClose={() => setComposerOpen(false)} title="Ask the community"><form onSubmit={submitQuestion} className="space-y-4"><input value={title} onChange={e => setTitle(e.target.value)} maxLength={200} placeholder="What do you want to ask?" className="w-full rounded-xl border px-4 py-3 text-sm dark:bg-zinc-800 dark:border-dark-border" /><textarea value={content} onChange={e => setContent(e.target.value)} maxLength={5000} placeholder="Add context so fellow students can give a useful answer..." className="w-full h-36 resize-none rounded-xl border px-4 py-3 text-sm dark:bg-zinc-800 dark:border-dark-border" /><div className="relative"><Tag className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={tags} onChange={e => setTags(e.target.value)} maxLength={500} placeholder="Tags, comma separated (e.g. DSA, Java, Interviews)" className="w-full rounded-xl border pl-9 pr-4 py-3 text-sm dark:bg-zinc-800 dark:border-dark-border" /></div><button disabled={postQuestion.isPending} className="w-full inline-flex justify-center gap-2 rounded-xl bg-brand-650 text-white py-3 text-sm font-bold disabled:opacity-60">{postQuestion.isPending && <Loader2 className="h-4 w-4 animate-spin" />} Post question</button></form></Modal>}
    {selectedId && <Modal onClose={() => { setSelectedId(null); setAnswer(''); }} title="Question and answers">{questionQuery.isLoading ? <div className="py-12 text-center"><Loader2 className="h-6 w-6 animate-spin mx-auto" /></div> : selectedQuestion && <div className="space-y-6"><QuestionCard question={selectedQuestion} onOpen={() => {}} compact /><div className="border-t pt-5 dark:border-dark-border"><h3 className="font-bold text-slate-800 dark:text-white mb-4">{selectedQuestion.answerCount} {selectedQuestion.answerCount === 1 ? 'answer' : 'answers'}</h3><div className="space-y-4">{selectedQuestion.answers.map(item => <div key={item.id} className="rounded-xl bg-slate-50 dark:bg-zinc-800/60 p-4"><div className="flex items-center gap-2 text-xs text-slate-500"><UserRound className="h-3.5 w-3.5" /><b>{item.authorName}</b><span>· {formatDate(item.createdAt)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-slate-700 dark:text-slate-300">{item.content}</p></div>)}</div></div><form onSubmit={submitAnswer} className="border-t pt-5 dark:border-dark-border"><label className="font-bold text-sm text-slate-800 dark:text-white">Your answer</label><textarea value={answer} onChange={e => setAnswer(e.target.value)} maxLength={5000} placeholder="Share a helpful answer..." className="mt-2 h-28 w-full resize-none rounded-xl border px-4 py-3 text-sm dark:bg-zinc-800 dark:border-dark-border" /><button disabled={postAnswer.isPending} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-brand-650 text-white px-4 py-2.5 text-sm font-bold disabled:opacity-60"><Send className="h-4 w-4" /> {postAnswer.isPending ? 'Posting...' : 'Post answer'}</button></form></div>}</Modal>}
  </div>;
};

const QuestionCard: React.FC<{ question: CommunityQuestion; onOpen: () => void; compact?: boolean }> = ({ question, onOpen, compact }) => <article className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-dark-border dark:bg-dark-card"><div className="flex gap-3"><div className="min-w-16 text-center text-xs text-slate-500"><MessageCircle className="h-5 w-5 mx-auto text-brand-600" /><b className="block mt-1 text-slate-700 dark:text-slate-200">{question.answerCount}</b> answers</div><div className="min-w-0 flex-1"><button onClick={onOpen} className="text-left text-lg font-bold text-slate-800 hover:text-brand-650 dark:text-white">{question.title}</button><p className={`mt-2 whitespace-pre-wrap text-sm leading-relaxed text-slate-600 dark:text-slate-300 ${compact ? '' : 'line-clamp-3'}`}>{question.content}</p><div className="mt-3 flex flex-wrap gap-2">{question.tags.map(tag => <span key={tag} className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700 dark:bg-brand-900/20 dark:text-brand-300">{tag}</span>)}</div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span className="flex items-center gap-1"><UserRound className="h-3.5 w-3.5" /> {question.authorName}</span><span>{formatDate(question.createdAt)}</span></div>{!compact && <button onClick={onOpen} className="mt-4 text-sm font-bold text-brand-650 hover:text-brand-700">View question & answer</button>}</div></div></article>;
const Modal: React.FC<{ title: string; onClose: () => void; children: React.ReactNode }> = ({ title, onClose, children }) => <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div onClick={onClose} className="absolute inset-0 bg-slate-950/50" /><div className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-dark-card"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold dark:text-white">{title}</h2><button onClick={onClose} className="rounded-lg p-1 text-slate-500 hover:bg-slate-100 dark:hover:bg-zinc-800"><X className="h-5 w-5" /></button></div>{children}</div></div>;
